# Data preprocessing

Raw datasets are in a CSV format. They were converted from the original formats including .dsc (Disco project file, BPIC 2015), .xes (BPIC 2017), and .xlsx (the proprietary data).

In [31]:
import pandas as pd

In [32]:
log_name = 'propr'

fn_logs = {
    'propr': './data/proprietary_anony.csv'
    # 'propr': './data/proprietary.csv'
}

In [33]:
log = pd.read_csv(fn_logs[log_name])
# drop rows or columns with all values as NA
log = log.dropna(how='all')
log

,Activity,PI_ID,Start,End,Originator,Weekday,Cost,"School holidays; 0 = no, 1 = yes",Approval; 1 = low risk to 4 = high risk,Type of loan; 0 = normal; 1 = special
0,Approval_Branch,ID-1,18/11/2010 15:27,18/11/2010 15:58,004-9-1,Thursday,"0,87 € per minute",0.0,2.0,0.0
1,Precheck,ID-1,19/11/2010 12:45,19/11/2010 12:46,000-3-01,Friday,"0,87 € per minute",0.0,2.0,0.0
2,Precheck,ID-1,24/11/2010 8:18,24/11/2010 8:26,000-2-01,Wednesday,"0,87 € per minute",0.0,2.0,0.0
3,Check_of_Processing_Applications,ID-1,24/11/2010 10:35,24/11/2010 10:35,000-2-01,Wednesday,"0,87 € per minute",0.0,2.0,0.0
4,Processing_of_Applications,ID-1,2/12/2010 10:46,2/12/2010 10:46,010-23-11,Thursday,"1,02 € per minute",0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...
18440,Precheck,ID-1731,13/12/2010 11:38,13/12/2010 11:40,000-2-01,Monday,"0,87 € per minute",0.0,2.0,0.0
18441,Check_of_Processing_Applications,ID-1731,13/12/2010 12:06,13/12/2010 12:14,000-2-01,Monday,"0,87 € per minute",0.0,2.0,0.0
18442,Processing_of_Applications,ID-1731,22/12/2010 11:48,22/12/2010 11:48,010-23-07,Wednesday,"1,02 € per minute",1.0,2.0,0.0
18443,Archieving,ID-1731,22/12/2010 11:49,22/12/2010 13:19,010-23-07,Wednesday,"1,02 € per minute",1.0,2.0,0.0
18444,End,ID-1731,22/12/2010 13:19,22/12/2010 13:19,010-23-07,Wednesday,"1,02 € per minute",1.0,2.0,0.0

In [34]:
log.columns

Index(['Activity', 'PI_ID', 'Start', 'End', 'Originator', 'Weekday', 'Cost',
       'School holidays; 0 = no, 1 = yes',
       'Approval; 1 = low risk to 4 = high risk',
       'Type of loan; 0 = normal; 1 = special'],
      dtype='object')

In [35]:
if log_name == 'bpic15':
    print('#Cases:\t{}'.format(log['Case ID'].nunique()))
    print('#Activities:\t{}'.format(log['activity'].nunique()))
    print('#Resources:\t{}'.format(log['Resource'].nunique()))

if log_name == 'bpic17':
    print('#Cases:\t{}'.format(log['case:concept:name'].nunique()))
    print('#Activities:\t{}'.format(log['concept:name'].nunique()))
    print('#Resources:\t{}'.format(log['org:resource'].nunique()))
    print(log['lifecycle:transition'].unique())

if log_name == 'propr':
    print('#Cases:\t{}'.format(log['PI_ID'].nunique()))
    print('#Activities:\t{}'.format(log['Activity'].nunique()))
    print('#Resources:\t{}'.format(log['Originator'].nunique()))

#Cases:	1731
#Activities:	25
#Resources:	220

In [36]:
COL_CASE_ID = 'case_id'
COL_ACTIVITY = 'activity'
COL_START_TS = 'start timestamp'
COL_COMPLETE_TS = 'complete timestamp'
COL_RESOURCE = 'resource'

if log_name == 'bpic15':
    log = log.rename(columns={
        'Case ID': COL_CASE_ID,
        'activity': COL_ACTIVITY,
        'Complete Timestamp': COL_COMPLETE_TS,
        'Resource': COL_RESOURCE
    })
    log.to_csv('./data/preproc/bpic15.csv', index=False)

if log_name == 'bpic17':
    pass

if log_name == 'propr':
    log = log.rename(columns={
        'PI_ID': COL_CASE_ID,
        'Activity': COL_ACTIVITY,
        'Start': COL_START_TS,
        'End': COL_COMPLETE_TS,
        'Originator': COL_RESOURCE
    })
    log.to_csv('./data/preproc/proprietary.csv', index=False)