# Gold Plating

## Description
Introducing higher levels of regulation or conducting more work, or [...] the addition of features or services that are not required

In [502]:
import pandas as pd
import numpy as np
import altair as alt

In [503]:
ref_log_name = 'propr_ref'
test_log_name = 'propr_test'

fn_logs = {
    'bpic15': '../data/preproc/bpic15.csv',
    'bpic15_ref': '../data/preproc/bpic15_train-70.csv',
    'bpic15_test': '../data/preproc/bpic15_test-30.csv',

    'bpic17': '../data/preproc/bpic2017.csv',

    'propr': '../data/preproc/proprietary.csv',
    'propr_ref': '../data/preproc/proprietary_train-70.csv',
    'propr_test': '../data/preproc/proprietary_test-30.csv'
}

In [504]:
log = pd.read_csv(fn_logs[test_log_name])
print(log['case_id'].nunique())
log

519

,activity,case_id,start timestamp,complete timestamp,resource,Weekday,Cost,"School holidays; 0 = no, 1 = yes",Approval; 1 = low risk to 4 = high risk,Type of loan; 0 = normal; 1 = special,_start timestamp,_complete timestamp
0,Application_Processing_Branches,ID-799,25/02/2011 16:01,2011-02-25 16:10:00,070-6-05,Friday,"1,02 € per minute",0.0,1.0,0.0,2011-02-25 16:01:00,2011-02-25 16:10:00
1,Precheck,ID-940,25/02/2011 16:06,2011-02-25 16:19:00,070-9-2,Friday,"1,02 € per minute",0.0,1.0,0.0,2011-02-25 16:06:00,2011-02-25 16:19:00
2,Precheck,ID-1078,28/02/2011 8:28,2011-02-28 09:02:00,001-6-02,Monday,"0,87 € per minute",0.0,1.0,0.0,2011-02-28 08:28:00,2011-02-28 09:02:00
3,Precheck,ID-546,28/02/2011 10:40,2011-02-28 10:45:00,080-10-03,Monday,"0,87 € per minute",0.0,1.0,0.0,2011-02-28 10:40:00,2011-02-28 10:45:00
4,Application_Processing_Branches,ID-1457,28/02/2011 10:10,2011-02-28 10:55:00,070-7-06,Monday,"1,02 € per minute",0.0,1.0,0.0,2011-02-28 10:10:00,2011-02-28 10:55:00
...,...,...,...,...,...,...,...,...,...,...,...,...
5285,Approval_Branch,ID-496,31/05/2011 14:41,2011-05-31 16:11:00,001-7-03,Tuesday,"0,87 € per minute",0.0,2.0,0.0,2011-05-31 14:41:00,2011-05-31 16:11:00
5286,Precheck,ID-1384,31/05/2011 16:20,2011-05-31 16:21:00,010-21-01,Tuesday,"0,87 € per minute",0.0,2.0,0.0,2011-05-31 16:20:00,2011-05-31 16:21:00
5287,Approval_Branch,ID-496,31/05/2011 16:29,2011-05-31 16:30:00,010-21-01,Tuesday,"0,87 € per minute",0.0,2.0,0.0,2011-05-31 16:29:00,2011-05-31 16:30:00
5288,Check_of_Documents,ID-99,31/05/2011 15:42,2011-05-31 16:30:00,010-23-06,Tuesday,"1,02 € per minute",0.0,2.0,0.0,2011-05-31 15:42:00,2011-05-31 16:30:00
5289,Precheck,ID-101,31/05/2011 18:27,2011-05-31 18:29:00,000-3-01,Tuesday,"0,87 € per minute",0.0,2.0,0.0,2011-05-31 18:27:00,2011-05-31 18:29:00

In [505]:
# encode activity labels as short names for presentation purpose

print('There exist {} unique activity labels'.format(
    log['activity'].nunique()
))

# use initial letters for encoding
act_labels_short = dict()
for label in log['activity'].unique():
    label_short = ''.join([w[0] for w in label.split('_')])
    act_labels_short[label] = label_short
print('There are {} short labels after encoding'.format(
    len(act_labels_short.values())
))
for k in sorted(act_labels_short.keys()):
    print('{:>50} -> {:>30}'.format(k, act_labels_short[k]))

log['activity_short'] = log['activity'].apply(
    lambda x: act_labels_short[x]
)

log['activity'] = log['activity_short']

There exist 25 unique activity labels
There are 25 short labels after encoding
                              Administrative_Tasks ->                             AT
                   Application_Processing_Branches ->                            APB
                                          Approval ->                              A
                                   Approval_Branch ->                             AB
                          Approval_Executive_Board ->                            AEB
                                        Archieving ->                              A
                                 Check_of_Approval ->                            CoA
                                Check_of_Documents ->                            CoD
                  Check_of_Processing_Applications ->                           CoPA
                                               End ->                              E
                                   Further_inquiry ->                             Fi
                         Get_Signature_of_Customer ->                           GSoC
                                          Precheck ->                              P
                 Preparation_Draft_Executive_Board ->                           PDEB
                    Preparation_Special_Processing ->                            PSP
                               Processing_Approval ->                             PA
                      Processing_Incomplete_Orders ->                            PIO
                                  Processing_Reply ->                             PR
                        Processing_of_Applications ->                            PoA
           Processing_of_Applications_Sonderkredit ->                           PoAS
                                  Refusal_Branches ->                             RB
                                          Revision ->                              R
                                   Rework_Branches ->                             RB
                                   Second_vote_KfW ->                            SvK
                                             Trash ->                              T

## Performance-GP-2

### Apply the given criteria to determine cases of interest (COI)

In [506]:
# proprietary: 
# case types as types of loan

log['case_type'] = log.apply(
    lambda row: (
        'high_risk_loan' if (
            row['Approval; 1 = low risk to 4 = high risk'] == 4
        ) else 
        'other_loan'
    ),
    axis=1
)

print(log['case_type'].unique())

ct_coi = 'high_risk_loan'

print(log.loc[log['case_type'] == ct_coi, 'case_id'].nunique())

# investigate only COI
log = log[log['case_type'] == ct_coi]

ct_coi

['other_loan' 'high_risk_loan']
8

'high_risk_loan'

### Check within COI for cases with rare activities and long duration time

In [507]:
# check rare activities within the COI cohort
case_dist = []
for case_id in log['case_id'].unique():
    act = set(log.loc[log['case_id'] == case_id, 'activity'].unique())
    act_others = set(log.loc[log['case_id'] != case_id, 'activity'].unique())

    case_dist.append({
        'case_id': case_id,
        'uniq_activities': ','.join(a for a in act.difference(act_others)),
        'num_uniq_activities': len(act.difference(act_others))
    })
case_dist = pd.DataFrame(case_dist)

for case_id, events in log.groupby('case_id'):
    activities = events['activity'].unique()
    print(case_id)
    print(events.iloc[0])
    print(sorted(activities))
case_dist

ID-11
activity                                                    AB
case_id                                                  ID-11
start timestamp                                9/03/2011 10:28
complete timestamp                         2011-03-09 10:55:00
resource                                             040-10-01
Weekday                                              Wednesday
Cost                                         0,87 € per minute
School holidays; 0 = no, 1 = yes                           0.0
Approval; 1 = low risk to 4 = high risk                    4.0
Type of loan; 0 = normal; 1 = special                      0.0
_start timestamp                           2011-03-09 10:28:00
_complete timestamp                        2011-03-09 10:55:00
activity_short                                              AB
case_type                                       high_risk_loan
Name: 304, dtype: object
['A', 'AB', 'AEB', 'APB', 'CoPA', 'E', 'P', 'PDEB', 'PoA']
ID-1655
activity                                                  PDEB
case_id                                                ID-1655
start timestamp                               13/05/2011 14:15
complete timestamp                         2011-05-13 14:46:00
resource                                             100-10-01
Weekday                                                 Friday
Cost                                         0,87 € per minute
School holidays; 0 = no, 1 = yes                           0.0
Approval; 1 = low risk to 4 = high risk                    4.0
Type of loan; 0 = normal; 1 = special                      0.0
_start timestamp                           2011-05-13 14:15:00
_complete timestamp                        2011-05-13 14:46:00
activity_short                                            PDEB
case_type                                       high_risk_loan
Name: 4154, dtype: object
['A', 'AB', 'AEB', 'APB', 'CoPA', 'P', 'PDEB']
ID-243
activity                                                  PDEB
case_id                                                 ID-243
start timestamp                                18/04/2011 9:15
complete timestamp                         2011-04-18 09:47:00
resource                                               083-9-1
Weekday                                                 Monday
Cost                                         0,87 € per minute
School holidays; 0 = no, 1 = yes                           1.0
Approval; 1 = low risk to 4 = high risk                    4.0
Type of loan; 0 = normal; 1 = special                      0.0
_start timestamp                           2011-04-18 09:15:00
_complete timestamp                        2011-04-18 09:47:00
activity_short                                            PDEB
case_type                                       high_risk_loan
Name: 2520, dtype: object
['A', 'AEB', 'CoPA', 'E', 'GSoC', 'P', 'PDEB', 'PoA', 'RB']
ID-33
activity                                                    AB
case_id                                                  ID-33
start timestamp                                 5/04/2011 8:57
complete timestamp                         2011-04-05 14:08:00
resource                                               070-8-2
Weekday                                                Tuesday
Cost                                         1,02 € per minute
School holidays; 0 = no, 1 = yes                           0.0
Approval; 1 = low risk to 4 = high risk                    4.0
Type of loan; 0 = normal; 1 = special                      0.0
_start timestamp                           2011-04-05 08:57:00
_complete timestamp                        2011-04-05 14:08:00
activity_short                                              AB
case_type                                       high_risk_loan
Name: 1675, dtype: object
['A', 'AB', 'AEB', 'CoD', 'CoPA', 'E', 'P', 'PA', 'PDEB', 'PoA', 'RB']
ID-40
activity                                                     P
case_id                                                  ID-40
start timestamp                               25/03/2011 13:29
complete timestamp                         2011-03-25 14:05:00
resource                                             001-15-02
Weekday                                                 Friday
Cost                                         0,87 € per minute
School holidays; 0 = no, 1 = yes                           0.0
Approval; 1 = low risk to 4 = high risk                    4.0
Type of loan; 0 = normal; 1 = special                      0.0
_start timestamp                           2011-03-25 13:29:00
_complete timestamp                        2011-03-25 14:05:00
activity_short                                               P
case_type                                       high_risk_loan
Name: 1218, dtype: object
['AEB', 'APB', 'P', 'PDEB', 'PIO']
ID-431
activity                                                     P
case_id                                                 ID-431
start timestamp                                13/04/2011 9:49
complete timestamp                         2011-04-13 10:05:00
resource                                             001-15-02
Weekday                                              Wednesday
Cost                                         0,87 € per minute
School holidays; 0 = no, 1 = yes                           0.0
Approval; 1 = low risk to 4 = high risk                    4.0
Type of loan; 0 = normal; 1 = special                      0.0
_start timestamp                           2011-04-13 09:49:00
_complete timestamp                        2011-04-13 10:05:00
activity_short                                               P
case_type                                       high_risk_loan
Name: 2172, dtype: object
['A', 'AEB', 'APB', 'CoPA', 'E', 'P', 'PDEB', 'PIO', 'PoA']
ID-636
activity                                                    AB
case_id                                                 ID-636
start timestamp                                4/04/2011 14:44
complete timestamp                         2011-04-04 16:54:00
resource                                             001-15-01
Weekday                                                 Monday
Cost                                         0,87 € per minute
School holidays; 0 = no, 1 = yes                           0.0
Approval; 1 = low risk to 4 = high risk                    4.0
Type of loan; 0 = normal; 1 = special                      0.0
_start timestamp                           2011-04-04 14:44:00
_complete timestamp                        2011-04-04 16:54:00
activity_short                                              AB
case_type                                       high_risk_loan
Name: 1624, dtype: object
['A', 'AB', 'AEB', 'APB', 'CoPA', 'E', 'P', 'PDEB', 'PIO', 'PoA']
ID-97
activity                                                    AB
case_id                                                  ID-97
start timestamp                               29/04/2011 13:20
complete timestamp                         2011-04-29 13:44:00
resource                                             020-11-01
Weekday                                                 Friday
Cost                                         0,87 € per minute
School holidays; 0 = no, 1 = yes                           1.0
Approval; 1 = low risk to 4 = high risk                    4.0
Type of loan; 0 = normal; 1 = special                      0.0
_start timestamp                           2011-04-29 13:20:00
_complete timestamp                        2011-04-29 13:44:00
activity_short                                              AB
case_type                                       high_risk_loan
Name: 3219, dtype: object
['A', 'AB', 'AEB', 'CoPA', 'E', 'GSoC', 'P', 'PDEB', 'PIO', 'PoA', 'RB']

   case_id uniq_activities  num_uniq_activities
0    ID-11                                    0
1    ID-40                                    0
2   ID-636                                    0
3    ID-33          CoD,PA                    2
4   ID-431                                    0
5   ID-243                                    0
6    ID-97                                    0
7  ID-1655                                    0

In [508]:
# check case duration
df_case_time = []
for case_id, events in log.groupby('case_id'):
    df_case_time.append({
        'case_id': case_id,
        'case_duration_minutes': (
            pd.to_datetime(events['_complete timestamp']).max() -
            pd.to_datetime(events['_start timestamp']).min()
        ).total_seconds() / 60,
        'case_type': events.iloc[0]['case_type']
    })
df_case_time = pd.DataFrame(df_case_time)
df_case_time

   case_id  case_duration_minutes       case_type
0    ID-11                40490.0  high_risk_loan
1  ID-1655                17372.0  high_risk_loan
2   ID-243                21932.0  high_risk_loan
3    ID-33                63351.0  high_risk_loan
4    ID-40                66302.0  high_risk_loan
5   ID-431                28713.0  high_risk_loan
6   ID-636                14466.0  high_risk_loan
7    ID-97                29009.0  high_risk_loan

In [509]:
alt.vconcat(
    alt.Chart(df_case_time).mark_boxplot().encode(
        x='case_duration_minutes:Q'
    ),
    alt.Chart(df_case_time).mark_bar().encode(
        x='case_id:O',
        y='case_duration_minutes:Q'
    )
)
# alt.Chart(df_case_time).mark_bar().encode(
#     x=alt.X('case_duration_minutes:Q').bin(),
#     y='count():Q'
# )

alt.VConcatChart(...)